### ISSUE TITLE
Logging doesn't export valid GELF

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cafe.coffee.carsten#1]
**Original report on BitBucket by CESSDA Support Team (GitHub: [cessda](https://github.com/cessda)).**

----------------------------------------

GELF expects syslog levels given in numerical values. The current GELF formatter present in this application exports them in string format \(should export 7 in place of debug\).

**Comment by schildwaechter** [comment]
Fixed in current version
